---transactions
CREATE TABLE IF NOT EXISTS raw.transactions(
    new_mr TEXT,
    new_er TEXT,
    gender TEXT,
    city TEXT,
    --should this appear in the people table only? Can it differ for the same patient during different visits?,
    area TEXT,
    --should this appear in the people table only? Can it differ for the same patient during different visits?,
    age_years NUMERIC,
    triage_datetime TIMESTAMP,
    triagecomplaint TEXT,
    bp TEXT,
    tr_pulse NUMERIC,
    tr_temp NUMERIC,
    tr_resp NUMERIC,
    acuity TEXT,
    visit_datetime TIMESTAMP,
    systolic NUMERIC,
    diastolic NUMERIC,
    temperature NUMERIC,
    weight NUMERIC,
    o2sat NUMERIC,
    nurse_id TEXT,
    disposition TEXT,
    disposition_time TIMESTAMP,
    hopi TEXT,
    ed_dx TEXT,
    doctor_id TEXT,
    specialty TEXT,
    admission_date TEXT,
    admission_ward TEXT,
    discharge_ward TEXT,
    discharge_datetime TEXT
);